ArmyManagementSystem/Controllers/StaffMembersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ArmyManagementSystem.Data;
using ArmyManagementSystem.Models;

namespace ArmyManagementSystem.Controllers
{
    public class StaffMembersController : Controller
    {
        private readonly ArmyManagementSystemDbContext _context;

        public StaffMembersController(ArmyManagementSystemDbContext context)
        {
            _context = context;
        }

        // GET: StaffMembers
        public async Task<IActionResult> Index()
        {
              return _context.StaffMembers != null ? 
                          View(await _context.StaffMembers.ToListAsync()) :
                          Problem("Entity set 'ArmyManagementSystemDbContext.StaffMembers'  is null.");
        }

        // GET: StaffMembers/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staffMember = await _context.StaffMembers.FirstOrDefaultAsync(m => m.StaffMemberId == id);

            if (staffMember == null)
            {
                return NotFound();
            }

            return View(staffMember);
        }

        // GET: StaffMembers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StaffMembers/Create        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StaffMemberId,SerialNumber,Rank,Surname,Name,FatherName,DateOfBirth,ColorOfHair,ColorOfEyes,Height,BloodType,Address,PhoneNumber,Email")] StaffMember staffMember)
        {
            if (ModelState.IsValid)
            {
                staffMember.StaffMemberId = Guid.NewGuid();
                _context.Add(staffMember);
                await _context.SaveChangesAsync();
                TempData["CreateStaffMemberSuccess"] = "Το νέο μέλος προσωπικού δημιουργήθηκε επιτυχώς!";
                return RedirectToAction(nameof(Index));
            }
            return View(staffMember);
        }

        // GET: StaffMembers/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.StaffMembers == null)
            {
                return NotFound();
            }

            var staffMember = await _context.StaffMembers.FindAsync(id);

            if (staffMember == null)
            {
                return NotFound();
            }			
			return View(staffMember);
        }

        // POST: StaffMembers/Edit/5        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("StaffMemberId,SerialNumber,Rank,Surname,Name,FatherName,DateOfBirth,ColorOfHair,ColorOfEyes,Height,BloodType,Address,PhoneNumber,Email")] StaffMember staffMember)
        {
            if (id != staffMember.StaffMemberId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(staffMember);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StaffMemberExists(staffMember.StaffMemberId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
				TempData["EditStaffMemberSuccess"] = "Το μέλος προσωπικού ενημερώθηκε επιτυχώς!";
				return RedirectToAction(nameof(Index));
            }
            return View(staffMember);
        }

        // GET: StaffMembers/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.StaffMembers == null)
            {
                return NotFound();
            }

            var staffMember = await _context.StaffMembers.FirstOrDefaultAsync(m => m.StaffMemberId == id);
            
            if (staffMember == null)
            {
                return NotFound();
            }

            return View(staffMember);
        }

        // POST: StaffMembers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.StaffMembers == null)
            {
                return Problem("Entity set 'ArmyManagementSystemDbContext.StaffMembers'  is null.");
            }

            var staffMember = await _context.StaffMembers.FindAsync(id);

            if (staffMember != null)
            {
                _context.StaffMembers.Remove(staffMember);
            }
            
            await _context.SaveChangesAsync();
			TempData["DeleteStaffMemberSuccess"] = "Το μέλος προσωπικού διαγράφηκε επιτυχώς!";
			return RedirectToAction(nameof(Index));
        }

        private bool StaffMemberExists(Guid id)
        {
          return (_context.StaffMembers?.Any(e => e.StaffMemberId == id)).GetValueOrDefault();
        }
    }
}

ArmyManagementSystem/Controllers/StatisticsController.cs
using ArmyManagementSystem.Data;
using ArmyManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ArmyManagementSystem.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly ArmyManagementSystemDbContext _context;

        public StatisticsController(ArmyManagementSystemDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            // Retrieve the leave requests for the current year
            var leaveRequests = await _context.LeaveRequests
                .Where(lr => lr.StartDate.Year == DateTime.UtcNow.Year)
                .ToListAsync();

			ViewBag.MonthlyLeaveRequestCounts = GenerateMonthlyLeaveRequestCounts(leaveRequests);

            ViewBag.WeeklyLeaveRequestCounts = GenerateWeeklyLeaveRequestCounts(leaveRequests);

            ViewBag.DailyLeaveRequestCounts = GenerateDailyLeaveRequestCounts(leaveRequests);

            ViewBag.LeaveTypeCounts = GenerateLeaveTypeCounts(leaveRequests);
            
            ViewBag.MaxLeaveDays = leaveRequests.Max(lr => lr.LeaveDays);
            
            ViewBag.MinLeaveDays = leaveRequests.Min(lr => lr.LeaveDays);

            ViewBag.AvgLeaveDays = leaveRequests.Average(lr => lr.LeaveDays).ToString("0.##");

            return View();
        }

        /// <summary>
        /// Generates an array of monthly leave request counts for the current year.
        /// </summary>
        /// <param name="leaveRequests">The list of leave requests to count.</param>
        /// <returns>An array of dynamic objects representing the monthly leave request counts.</returns>
        private dynamic[] GenerateMonthlyLeaveRequestCounts(List<LeaveRequest> leaveRequests)
        {
            var currentYear = DateTime.UtcNow.Year;
            var monthlyLeaveRequestCounts = new dynamic[12]; // Array to store monthly counts

            for (int i = 0; i < 12; i++)
            {
                // Get the month name in the format "MMM yyyy" (e.g., "Jan 2023")
                var monthName = new DateTime(currentYear, i + 1, 1).ToString("MMM yyyy");

                // Count the leave requests whose starting date belongs to the current month
                var count = leaveRequests.Count(lr => lr.StartDate.Month == i + 1);

                // Create an anonymous object representing the month and its corresponding count
                monthlyLeaveRequestCounts[i] = new { label = monthName, y = count };
            }

            return monthlyLeaveRequestCounts;
        }


        /// <summary>
        /// Generates an array of weekly leave request counts within a specified range of weeks.
        /// </summary>
        /// <param name="leaveRequests">The list of leave requests to count.</param>
        /// <returns>An array of dynamic objects representing the weekly leave request counts.</returns>
        private dynamic[] GenerateWeeklyLeaveRequestCounts(List<LeaveRequest> leaveRequests)
        {
            var currentYear = DateTime.UtcNow.Year;
            var startDate = new DateTime(currentYear, 1, 1); // Start from the first day of the current year
            var endDate = new DateTime(currentYear, 12, 31); // Go up to the last day of the current year
            var weeklyLeaveRequestCounts = new List<dynamic>();

            var currentDate = startDate;
            while (currentDate <= endDate)
            {
                var weekEnd = currentDate.AddDays(6); // Each week lasts for 7 days

                var weekRange = currentDate.ToString("MMM d") + " - " + weekEnd.ToString("MMM d, yyyy");
                var count = leaveRequests.Count(lr => lr.StartDate >= currentDate && lr.StartDate <= weekEnd);
                weeklyLeaveRequestCounts.Add(new { label = weekRange, y = count });

                currentDate = weekEnd.AddDays(1); // Move to the next week
            }

            return weeklyLeaveRequestCounts.ToArray();
        }


        /// <summary>
        /// Generates daily leave request counts for each day of the current month based on the given list of leave requests.
        /// </summary>
        /// <param name="leaveRequests">The list of leave requests to analyze.</param>
        /// <returns>An array of dynamic objects representing the daily leave request counts.</returns>
        private dynamic[] GenerateDailyLeaveRequestCounts(List<LeaveRequest> leaveRequests)
        {
            // Get the current date in UTC
            var currentDate = DateTime.UtcNow.Date;

            // Determine the start date as the first day of the current month
            var startDate = new DateTime(currentDate.Year, currentDate.Month, 1);

            // Determine the end date as the last day of the current month
            var endDate = startDate.AddMonths(1).AddDays(-1);

            // Create an array to store the daily leave request counts
            var dailyLeaveRequestCounts = new dynamic[endDate.Day];

            for (int i = 0; i < endDate.Day; i++)
            {
                // Calculate the date for the current iteration
                var date = startDate.AddDays(i);

                // Count the number of leave requests that start on the current date
                var count = leaveRequests.Count(lr => lr.StartDate.Date == date);

                // Create an anonymous object representing the date and its corresponding count
                var dailyCountObject = new { label = date.ToString("MMM d"), y = count };

                dailyLeaveRequestCounts[i] = dailyCountObject;
            }

            return dailyLeaveRequestCounts;
        }


        /// <summary>
        /// Generates counts for each distinct leave type in the given list of leave requests.
        /// </summary>
        /// <param name="leaveRequests">The list of leave requests to analyze.</param>
        /// <returns>An array of dynamic objects representing the leave type counts.</returns>
        private dynamic[] GenerateLeaveTypeCounts(List<LeaveRequest> leaveRequests)
        {
            // Get distinct leave types from the leave requests
            var distinctLeaveTypes = leaveRequests.Select(lr => lr.LeaveType).Distinct().ToList();

            // Create an array to store leave type counts
            var leaveTypeCounts = new dynamic[distinctLeaveTypes.Count];

            for (int i = 0; i < distinctLeaveTypes.Count; i++)
            {
                var currentLeaveType = distinctLeaveTypes[i];

                // Count the number of leave requests with the current leave type
                var leaveTypeCount = leaveRequests.Count(lr => lr.LeaveType == currentLeaveType);

                // Create an anonymous object representing the leave type and its corresponding count
                var leaveTypeCountObject = new { label = currentLeaveType, y = leaveTypeCount };

                leaveTypeCounts[i] = leaveTypeCountObject;
            }

            return leaveTypeCounts;
        }

    }
}

ArmyManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ArmyManagementSystem</title>
    <link rel="stylesheet" href="~/css/spacelab.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ArmyManagementSystem.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/v/bs5/dt-1.13.4/datatables.min.css" />
</head>
<body>
    <header>        
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">ArmyManagementSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">
                                Αρχική                                
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="StaffMembers" asp-action="Index">
                                Προσωπικό
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Statistics" asp-action="Index">
                                Στατιστικά
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ArmyManagementSystem
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/v/bs5/dt-1.13.4/datatables.min.js"></script>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ArmyManagementSystem/Views/Shared/_Notifications.cshtml
@if (TempData["CreateStaffMemberSuccess"] != null)
{
	<div class="alert alert-dismissible alert-success mt-3">
		<button type="button" class="btn-close" data-bs-dismiss="alert"></button>
		<strong>@TempData["CreateStaffMemberSuccess"]</strong>
	</div>
}

@if (TempData["EditStaffMemberSuccess"] != null)
{
	<div class="alert alert-dismissible alert-success mt-3">
		<button type="button" class="btn-close" data-bs-dismiss="alert"></button>
		<strong>@TempData["EditStaffMemberSuccess"]</strong>
	</div>
}

@if (TempData["DeleteStaffMemberSuccess"] != null)
{
	<div class="alert alert-dismissible alert-success mt-3">
		<button type="button" class="btn-close" data-bs-dismiss="alert"></button>
		<strong>@TempData["DeleteStaffMemberSuccess"]</strong>
	</div>
}

@if (TempData["CreateLeaveRequestSuccess"] != null)
{
	<div class="alert alert-dismissible alert-success mt-3">
		<button type="button" class="btn-close" data-bs-dismiss="alert"></button>
		<strong>@TempData["CreateLeaveRequestSuccess"]</strong>
	</div>
}

@if (TempData["DeleteLeaveRequestSuccess"] != null)
{
	<div class="alert alert-dismissible alert-success mt-3">
		<button type="button" class="btn-close" data-bs-dismiss="alert"></button>
		<strong>@TempData["DeleteLeaveRequestSuccess"]</strong>
	</div>
}